# Generated by Django 3.1.5 on 2021-02-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymemo',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_memo_book', to='engineer.book'),
        ),
    ]
